/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CarListing {
    id: bigint;
    status: string;
    interiorImages360: Array<string>;
    model: string;
    postedAt: bigint;
    mileage: bigint;
    bookedAt?: bigint;
    imageUrls: Array<string>;
    sellerPhone: string;
    askingPrice: bigint;
    city: string;
    make: string;
    color: string;
    year: bigint;
    description: string;
    registrationNumber: string;
    sellerName: string;
    bookingStatus: string;
    transmission: string;
    fuelType: string;
    exteriorImages360: Array<string>;
    receiptFileName?: string;
}
export interface CallbackRequest {
    id: bigint;
    customerName: string;
    listingId: bigint;
    preferredTime: string;
    phone: string;
    requestedAt: bigint;
}
export interface backendInterface {
    addCallbackRequest(listingId: bigint, customerName: string, phone: string, preferredTime: string): Promise<bigint>;
    bookCar(id: bigint): Promise<void>;
    createListing(make: string, model: string, year: bigint, mileage: bigint, fuelType: string, transmission: string, color: string, city: string, askingPrice: bigint, sellerName: string, sellerPhone: string, description: string, imageUrls: Array<string>, exteriorImages360: Array<string>, interiorImages360: Array<string>, registrationNumber: string): Promise<bigint>;
    deleteListing(id: bigint): Promise<void>;
    filterCarListings(make: string | null, minPrice: bigint | null, maxPrice: bigint | null, year: bigint | null, fuelType: string | null, city: string | null): Promise<Array<CarListing>>;
    getAllBookingRecords(): Promise<Array<CarListing>>;
    getAllCallbackRequests(): Promise<Array<CallbackRequest>>;
    getAllListings(): Promise<Array<CarListing>>;
    getBankDetails(): Promise<string>;
    getCallbackRequestsByListingId(listingId: bigint): Promise<Array<CallbackRequest>>;
    getListingById(id: bigint): Promise<CarListing>;
    getListingByRegistrationNumber(registrationNumber: string): Promise<CarListing | null>;
    submitReceipt(listingId: bigint, receiptFileName: string): Promise<void>;
    updateListing(id: bigint, make: string, model: string, year: bigint, mileage: bigint, fuelType: string, transmission: string, color: string, city: string, askingPrice: bigint, sellerName: string, sellerPhone: string, description: string, imageUrls: Array<string>, exteriorImages360: Array<string>, interiorImages360: Array<string>, registrationNumber: string, status: string): Promise<void>;
    updateListingImages(id: bigint, imageUrls: Array<string>, exteriorImages360: Array<string>, interiorImages360: Array<string>): Promise<void>;
}
import type { CarListing as _CarListing } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCallbackRequest(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCallbackRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCallbackRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async bookCar(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookCar(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookCar(arg0);
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: string, arg10: string, arg11: string, arg12: Array<string>, arg13: Array<string>, arg14: Array<string>, arg15: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            return result;
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async filterCarListings(arg0: string | null, arg1: bigint | null, arg2: bigint | null, arg3: bigint | null, arg4: string | null, arg5: string | null): Promise<Array<CarListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterCarListings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterCarListings(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookingRecords(): Promise<Array<CarListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookingRecords();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookingRecords();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCallbackRequests(): Promise<Array<CallbackRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCallbackRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCallbackRequests();
            return result;
        }
    }
    async getAllListings(): Promise<Array<CarListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankDetails(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankDetails();
            return result;
        }
    }
    async getCallbackRequestsByListingId(arg0: bigint): Promise<Array<CallbackRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallbackRequestsByListingId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallbackRequestsByListingId(arg0);
            return result;
        }
    }
    async getListingById(arg0: bigint): Promise<CarListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingById(arg0);
                return from_candid_CarListing_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingById(arg0);
            return from_candid_CarListing_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingByRegistrationNumber(arg0: string): Promise<CarListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingByRegistrationNumber(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingByRegistrationNumber(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitReceipt(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReceipt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReceipt(arg0, arg1);
            return result;
        }
    }
    async updateListing(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string, arg9: bigint, arg10: string, arg11: string, arg12: string, arg13: Array<string>, arg14: Array<string>, arg15: Array<string>, arg16: string, arg17: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
            return result;
        }
    }
    async updateListingImages(arg0: bigint, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingImages(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingImages(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_CarListing_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarListing): CarListing {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarListing]): CarListing | null {
    return value.length === 0 ? null : from_candid_CarListing_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    interiorImages360: Array<string>;
    model: string;
    postedAt: bigint;
    mileage: bigint;
    bookedAt: [] | [bigint];
    imageUrls: Array<string>;
    sellerPhone: string;
    askingPrice: bigint;
    city: string;
    make: string;
    color: string;
    year: bigint;
    description: string;
    registrationNumber: string;
    sellerName: string;
    bookingStatus: string;
    transmission: string;
    fuelType: string;
    exteriorImages360: Array<string>;
    receiptFileName: [] | [string];
}): {
    id: bigint;
    status: string;
    interiorImages360: Array<string>;
    model: string;
    postedAt: bigint;
    mileage: bigint;
    bookedAt?: bigint;
    imageUrls: Array<string>;
    sellerPhone: string;
    askingPrice: bigint;
    city: string;
    make: string;
    color: string;
    year: bigint;
    description: string;
    registrationNumber: string;
    sellerName: string;
    bookingStatus: string;
    transmission: string;
    fuelType: string;
    exteriorImages360: Array<string>;
    receiptFileName?: string;
} {
    return {
        id: value.id,
        status: value.status,
        interiorImages360: value.interiorImages360,
        model: value.model,
        postedAt: value.postedAt,
        mileage: value.mileage,
        bookedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.bookedAt)),
        imageUrls: value.imageUrls,
        sellerPhone: value.sellerPhone,
        askingPrice: value.askingPrice,
        city: value.city,
        make: value.make,
        color: value.color,
        year: value.year,
        description: value.description,
        registrationNumber: value.registrationNumber,
        sellerName: value.sellerName,
        bookingStatus: value.bookingStatus,
        transmission: value.transmission,
        fuelType: value.fuelType,
        exteriorImages360: value.exteriorImages360,
        receiptFileName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.receiptFileName))
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarListing>): Array<CarListing> {
    return value.map((x)=>from_candid_CarListing_n4(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
