/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallbackRequest {
  'id' : bigint,
  'customerName' : string,
  'listingId' : bigint,
  'preferredTime' : string,
  'phone' : string,
  'requestedAt' : bigint,
}
export interface CarListing {
  'id' : bigint,
  'status' : string,
  'interiorImages360' : Array<string>,
  'model' : string,
  'postedAt' : bigint,
  'mileage' : bigint,
  'bookedAt' : [] | [bigint],
  'imageUrls' : Array<string>,
  'sellerPhone' : string,
  'askingPrice' : bigint,
  'city' : string,
  'make' : string,
  'color' : string,
  'year' : bigint,
  'description' : string,
  'registrationNumber' : string,
  'sellerName' : string,
  'bookingStatus' : string,
  'transmission' : string,
  'fuelType' : string,
  'exteriorImages360' : Array<string>,
  'receiptFileName' : [] | [string],
}
export interface _SERVICE {
  'addCallbackRequest' : ActorMethod<[bigint, string, string, string], bigint>,
  'bookCar' : ActorMethod<[bigint], undefined>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      string,
    ],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'filterCarListings' : ActorMethod<
    [
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [string],
    ],
    Array<CarListing>
  >,
  'getAllBookingRecords' : ActorMethod<[], Array<CarListing>>,
  'getAllCallbackRequests' : ActorMethod<[], Array<CallbackRequest>>,
  'getAllListings' : ActorMethod<[], Array<CarListing>>,
  'getBankDetails' : ActorMethod<[], string>,
  'getCallbackRequestsByListingId' : ActorMethod<
    [bigint],
    Array<CallbackRequest>
  >,
  'getListingById' : ActorMethod<[bigint], CarListing>,
  'getListingByRegistrationNumber' : ActorMethod<[string], [] | [CarListing]>,
  'submitReceipt' : ActorMethod<[bigint, string], undefined>,
  'updateListing' : ActorMethod<
    [
      bigint,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      string,
      string,
    ],
    undefined
  >,
  'updateListingImages' : ActorMethod<
    [bigint, Array<string>, Array<string>, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];