/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'interiorImages360' : IDL.Vec(IDL.Text),
  'model' : IDL.Text,
  'postedAt' : IDL.Int,
  'mileage' : IDL.Nat,
  'bookedAt' : IDL.Opt(IDL.Int),
  'imageUrls' : IDL.Vec(IDL.Text),
  'sellerPhone' : IDL.Text,
  'askingPrice' : IDL.Nat,
  'city' : IDL.Text,
  'make' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'sellerName' : IDL.Text,
  'bookingStatus' : IDL.Text,
  'transmission' : IDL.Text,
  'fuelType' : IDL.Text,
  'exteriorImages360' : IDL.Vec(IDL.Text),
  'receiptFileName' : IDL.Opt(IDL.Text),
});
export const CallbackRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'listingId' : IDL.Nat,
  'preferredTime' : IDL.Text,
  'phone' : IDL.Text,
  'requestedAt' : IDL.Int,
});
export const CarInquiry = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'listingId' : IDL.Text,
  'submittedAt' : IDL.Int,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCallbackRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'bookCar' : IDL.Func([IDL.Nat], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'filterCarListings' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(CarListing)],
      ['query'],
    ),
  'getAllBookingRecords' : IDL.Func([], [IDL.Vec(CarListing)], ['query']),
  'getAllCallbackRequests' : IDL.Func(
      [],
      [IDL.Vec(CallbackRequest)],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(CarInquiry)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(CarListing)], ['query']),
  'getBankDetails' : IDL.Func([], [IDL.Text], ['query']),
  'getCallbackRequestsByListingId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CallbackRequest)],
      ['query'],
    ),
  'getInquiriesByListing' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CarInquiry)],
      ['query'],
    ),
  'getListingById' : IDL.Func([IDL.Nat], [CarListing], ['query']),
  'getListingByRegistrationNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CarListing)],
      ['query'],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitReceipt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateListingImages' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'interiorImages360' : IDL.Vec(IDL.Text),
    'model' : IDL.Text,
    'postedAt' : IDL.Int,
    'mileage' : IDL.Nat,
    'bookedAt' : IDL.Opt(IDL.Int),
    'imageUrls' : IDL.Vec(IDL.Text),
    'sellerPhone' : IDL.Text,
    'askingPrice' : IDL.Nat,
    'city' : IDL.Text,
    'make' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'sellerName' : IDL.Text,
    'bookingStatus' : IDL.Text,
    'transmission' : IDL.Text,
    'fuelType' : IDL.Text,
    'exteriorImages360' : IDL.Vec(IDL.Text),
    'receiptFileName' : IDL.Opt(IDL.Text),
  });
  const CallbackRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'listingId' : IDL.Nat,
    'preferredTime' : IDL.Text,
    'phone' : IDL.Text,
    'requestedAt' : IDL.Int,
  });
  const CarInquiry = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'listingId' : IDL.Text,
    'submittedAt' : IDL.Int,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addCallbackRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'bookCar' : IDL.Func([IDL.Nat], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'filterCarListings' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(CarListing)],
        ['query'],
      ),
    'getAllBookingRecords' : IDL.Func([], [IDL.Vec(CarListing)], ['query']),
    'getAllCallbackRequests' : IDL.Func(
        [],
        [IDL.Vec(CallbackRequest)],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(CarInquiry)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(CarListing)], ['query']),
    'getBankDetails' : IDL.Func([], [IDL.Text], ['query']),
    'getCallbackRequestsByListingId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CallbackRequest)],
        ['query'],
      ),
    'getInquiriesByListing' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CarInquiry)],
        ['query'],
      ),
    'getListingById' : IDL.Func([IDL.Nat], [CarListing], ['query']),
    'getListingByRegistrationNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CarListing)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitReceipt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateListingImages' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };